language: node_js
node_js:
  - 5.1.0
services:
  - postgresql
before_script:
  - java -version
  - psql -c "CREATE USER hpmcadmin WITH PASSWORD 'password1';" -U postgres
  - psql -c "ALTER USER hpmcadmin CREATEDB;" -U postgres
  - psql -c "ALTER USER hpmcadmin WITH SUPERUSER;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - node ttt.js &
  - wget https://www.dropbox.com/s/zt265xusoy13is7/z.tar.gz
  - pwd
  - ls
  - echo "@@@@@@@@@@@@@@@@@@@@@@"
  - sudo chmod +x aa.sh
  - ./aa.sh
  - cd hpmc/Schema
  - java -jar hp4m-database-jar-with-dependencies.jar -u postgres -p password  -i -port 5432 -ux 2 -home "/home/travis/build/mcfortravis/nodeTest/hpmc" 
  - cd ..
  - cd bin
  - ./start-jetty.sh
  - sleep 420
  
script: curl -H "Content-Type:application/json" -X POST -d '{name:"admin@default.com", password:"password", accountName:"default", locale:"en"}' "http://localhost:8080/rest/client/login"
script: java -cp . UploadApp