language: node_js
node_js:
  - 5.1.0
services:
  - postgresql
before_script:
  - java -version
  - chmod +x uploadapp.sh
  - psql -c "CREATE USER hpmcadmin WITH PASSWORD 'password1';" -U postgres
  - psql -c "ALTER USER hpmcadmin CREATEDB;" -U postgres
  - psql -c "ALTER USER hpmcadmin WITH SUPERUSER;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - node ttt.js &
  - wget https://www.dropbox.com/s/zt265xusoy13is7/z.tar.gz
  - pwd
  - ls
  - echo "@@@@@@@@@@@@@@@@@@@@@@"
  - export ANDROID_HOME=/home/travis/build/mcfortravis/nodeTest/hpmc_3rd_party/android-sdk-linux
  - echo $ANDROID_HOME
  - sudo chmod +x aa.sh
  - ./aa.sh
  - cp HP4M_ApkInfuser.sh hpmc/AndroidTools
  - cd hpmc/Schema
  - java -jar hp4m-database-jar-with-dependencies.jar -u postgres -p password  -i -port 5432 -ux 2 -home "/home/travis/build/mcfortravis/nodeTest/hpmc" 
  - cd ..
  - cd bin
  - ./start-jetty.sh
  - sleep 220
  - cd /home/travis/build/mcfortravis/nodeTest
  - ls
  - chmod -R 777 hpmc
  - echo $?
script: java -cp . UploadApp
after_script: 
  - echo -----------------------------===========
  - cat /home/travis/build/mcfortravis/nodeTest/hpmc/AndroidTools/ApkInfuser/log/ApkInfuser.log
  